// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace JsbSdk.Trade
{
    public class TradeCloseResponse
    {
        /// <summary>
        /// Only <see cref="Trade.Tid"/> and <see cref="Trade.Modified"/> will be available.
        /// </summary>
        [JsonProperty("trade")]
        public Trade Trade { get; set; }
    }

    public class JsbTradeCloseResponse : JsbResponse
    {
        [JsonProperty("trade_close_response")]
        public TradeCloseResponse TradeCloseResponse { get; set; }
    }

}
